image: gradle:7.3.3-jdk17-alpine

stages:
  - assemble
  - checkstyle
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

commons-assemble:
  stage: assemble
  script:
    gradle commons:assemble

commons-checkstyle:
  stage: checkstyle
  script:
    gradle commons:checkstyleMain commons:checkStyleTest
  allow_failure: true

commons-test:
  stage: test
  script:
    - gradle commons:test commons:jacocoTestReport
    - echo `cat commons/build/jacocoHtml/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  coverage: /TestCoverage:(\d+)%/
